development:
  adapter: postgresql
  database: group_project_database_development
  pool: 5
  timeout: 5000
  template: template0
  
test:
  adapter: postgresql
  database: group_project_database_test
  pool: 5
  timeout: 5000
  template: template0
  
production:
  adapter: postgresql
  database: group_project_database_production
  pool: 5
  timeout: 5000
  template: template0